usuario:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /

tienda:
    resource: "@TiendaBundle/Resources/config/routing.yml"
    prefix:   /

ciudad:
    resource: "@CiudadBundle/Resources/config/routing.yml"
    prefix:   /

oferta:
    resource: "@OfertaBundle/Resources/config/routing.yml"
    prefix:   /
# app/config/routing.yml
pagina_estatica:
    path:    /sitio/{pagina}
    defaults: { _controller: OfertaBundle:Sitio:estatica }

_pagina_estatica:
    path:    /sitio/{pagina}/
    defaults: { _controller: FrameworkBundle:Redirect:redirect,route: pagina_estatica, permanent:true }

# app/config/routing.yml
portada:
    path: /
    defaults: { _controller: OfertaBundle:Default:portada }