security:

    firewalls:
        
        # Firewall global utilizado en la parte pública o frontend
        frontend:
            pattern:        ^/*
            anonymous:      ~
            form_login:
                login_path: usuario_login
                check_path: usuario_login_check

    access_control:
        - { path: ^/usuario/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuario/registro, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuario/*, roles: ROLE_USUARIO }

    providers:
        # Usuarios del frontend
        usuarios:
            entity: { class: Cupon\UsuarioBundle\Entity\Usuario, property: email }

    encoders:
        Cupon\UsuarioBundle\Entity\Usuario: plaintext
